##################################################################################################
# BUILD args - will be passed into Dockerfile.rhtap and bundle.Dockerfile.rhtap in build pipelines
##################################################################################################

# VolSync version
ARG_VERSION=0.17.0
ARG_SUPPORTED_OCP_VERSIONS=v4.16-v5.0

# Mover versions
# These should match the versions in the drift-cache/volsync/Dockerfile.cached
ARG_RCLONE_VERSION=v1.75.0
ARG_RCLONE_GIT_HASH="9ee9d0a0cafd5e5fe3b271d2280b090ab6e64048"

ARG_SYNCTHING_VERSION=v1.30.0
ARG_SYNCTHING_GIT_HASH="0945304a79d6bbaeac7fc2cc1b06f57d3cf66622"

ARG_DISKRSYNC_VERSION=v1.3.0
ARG_DISKRSYNC_GIT_HASH="507805c4378495fc2267b77f6eab3d6bb318c86c"

# Related images - will need to be kept updated with latest via component nudges
# See https://konflux.pages.redhat.com/docs/users/building/component-nudges.html
#
# Note:  do NOT surround these with "" as this does something strange with the output from bundle-hack/update-bundle.sh
ARG_STAGE_VOLSYNC_IMAGE_PULLSPEC=quay.io/redhat-user-workloads/volsync-tenant/volsync-0-17@sha256:ff6bf27277291c169af12b6971513f9cbf0d22222211756d53a752c78ed011e1

#
# ACM 5.0 doclink
#
ARG_ACM_DOCLINK=https://docs.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/5.0/html/business_continuity/business-cont-overview#volsync
